# build_info.cmake
#
# Generates a header defining the Bisc8 build version string:
#
#     BISC8_BUILD_VERSION = "r<NNNN>-<YYYYMMDD>-<HHMM>[+]"
#
# where r<NNNN> is the zero-padded git commit count, <YYYYMMDD>-<HHMM> is the
# local build date/time, and a trailing "+" marks a build made with uncommitted
# changes to tracked files. The header is regenerated on every build so the
# timestamp always reflects the actual build.
#
# Usage:
#   cmake -DOUTPUT_FILE=<path> -DSRC_DIR=<dir inside repo> -P build_info.cmake

if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "build_info.cmake: OUTPUT_FILE is required")
endif()
if(NOT DEFINED SRC_DIR)
    set(SRC_DIR "${CMAKE_CURRENT_LIST_DIR}")
endif()

# Graceful fallbacks for builds without git (e.g. from a source tarball).
set(_rev "r----")
set(_sha "nogit")
set(_dirty "")

find_program(GIT_EXECUTABLE git)
if(GIT_EXECUTABLE)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-list --count HEAD
        WORKING_DIRECTORY "${SRC_DIR}"
        OUTPUT_VARIABLE _count
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE _count_rc)
    if(_count_rc EQUAL 0 AND NOT _count STREQUAL "")
        set(_padded "${_count}")
        string(LENGTH "${_padded}" _len)
        while(_len LESS 4)
            set(_padded "0${_padded}")
            string(LENGTH "${_padded}" _len)
        endwhile()
        set(_rev "r${_padded}")
    endif()

    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
        WORKING_DIRECTORY "${SRC_DIR}"
        OUTPUT_VARIABLE _sha_out
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE _sha_rc)
    if(_sha_rc EQUAL 0 AND NOT _sha_out STREQUAL "")
        set(_sha "${_sha_out}")
    endif()

    # Untracked files (scratch, generated headers, design drafts) must NOT mark
    # the build dirty -- only uncommitted changes to tracked files do.
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
        WORKING_DIRECTORY "${SRC_DIR}"
        OUTPUT_VARIABLE _status_out
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
    if(NOT _status_out STREQUAL "")
        set(_dirty "+")
    endif()
endif()

string(TIMESTAMP _date "%Y%m%d")
string(TIMESTAMP _time "%H%M")
set(_version "${_rev}-${_date}-${_time}${_dirty}")

set(_content "#pragma once\n")
string(APPEND _content "// Generated by build_info.cmake -- do not edit, not tracked in git.\n")
string(APPEND _content "#define BISC8_BUILD_VERSION \"${_version}\"\n")
string(APPEND _content "#define BISC8_BUILD_SHA \"${_sha}\"\n")

# Only rewrite when the content actually changes, so identical rebuilds within
# the same minute don't force a needless recompile.
set(_existing "")
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" _existing)
endif()
if(NOT _existing STREQUAL _content)
    file(WRITE "${OUTPUT_FILE}" "${_content}")
endif()

message(STATUS "Bisc8 build version: ${_version} (${_sha})")
